# Generated by Django 3.1.3 on 2020-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='image',
            field=models.ImageField(upload_to='blog-pics'),
        ),
    ]
